name: HIL

on:
  workflow_dispatch:
    inputs:
      title:
        required: true
  
run-name: ${{ github.event.inputs.title }}

jobs:
  hil:
    runs-on: self-hosted
    steps:
    - name: Print to console
      run: |
        echo "Running on the Pi!!"
        
    - name: Checkout repository
      uses: actions/checkout@v4
       
    - name: Install pytest
      run: |
        pip3 install -U pytest
        
    - name: Run pytest
      run: |
        python3 -m pytest
        
    - name: Set job status
      if: always()
      run: exit $(python3 -m pytest --failed -q | wc -l)
