name: Run Hardware Tests (Proxy)

on:
  workflow_dispatch:
  push:
  
jobs:
  hil:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # everything
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: not needed
    - name: Push changes to CI repository
      run: |
        git checkout -b hil-run
        git remote add ci git@github.com:StevensRockSat-C/RPi-Test-Runner.git
        git push -f -u ci hil-run
        sleep 5
    
    - name: Get commit details
      id: commit_details
      run: |
        COMMIT_MSG=$(git show -s --format=%s)
        echo "::set-output name=commit_message::$COMMIT_MSG"
        
    - name: Trigger and wait for HIL workflow
      uses: aurelien-baudet/workflow-dispatch@v2.1.1
      with:
        workflow: HIL.yml
        ref: hil-run
        repo: StevensRockSat-C/RPi-Test-Runner
        token: ${{ secrets.PRIVATE_CI_PERSONAL_ACCESS_TOKEN }}
        wait-for-completion: true
        workflow-logs: print
        inputs: '{"title": "$(git rev-parse --short "$GITHUB_SHA") Commit: ${{ steps.commit_details.outputs.commit_message }}; ${github.event.commits[0].author.name}"}'